# .github/workflows/release.yml

name: Publish to Maven Central and Create GitHub Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      # === Step 1: Setup Environment ===
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21 and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: ossrh
          # CORRECTED: Use the secret values, not literal strings
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_TOKEN }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      # === Step 2: Build and Deploy to Maven Central ===
      - name: Build and Deploy to Maven Central
        # The env block is no longer needed here, as setup-java has already configured settings.xml
        run: mvn -B -P release deploy

      # === Step 3: Build the Deployable WAR (without cleaning) ===
      - name: Build Deployable WAR
        run: mvn -B package -P deployable-war --file pom.xml

      # === Step 4: Create the GitHub Release and Upload All Artifacts ===
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/zello-vault-aggregator.jar
            target/zello-vault-aggregator-javadoc.jar
            target/zello-vault-aggregator-sources.jar
            target/zello-vault-aggregator.war
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}